spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
spring:
  thymeleaf:
    cache: true
          